### ISSUE TITLE
Safe-SVG v2.1.0 should not enqueue frontend stylesheet and JavaScript if Gutenberg block is not used

### ISSUE THREAD

**Issue by freinbichler** [darylldoyle/safe-svg#109]
### Is your enhancement related to a problem? Please describe.

The new version 2.1.0, which adds a Gutenberg block, enqueues the following files in the frontend of the website, even if this block is not used:
* safe-svg-block-frontend.css
* safe-svg-block-frontend.js

This is also mentioned in https://github.com/10up/safe-svg/pull/80#issuecomment-1482534927

The JS file is even empty (!). As a web agency focused on the performance of our websites, we keep an eye on every single CSS and JS file loaded in the frontend. Please do not enqueue CSS and JS files for unused functionality. Especially in a plugin, which previously only provided backend functionality (and we will still only use it for that).

Right now we have to add the following code to all of our websites using this plugin to dequeue these assets:
```php
wp_dequeue_style('safe-svg-block-frontend');
wp_deregister_script('safe-svg-block-script');
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IanDelMar** [comment]
I strongly agree. Additionally, I don't see the need for this little amount of CSS being stored in an extra stylesheet. I also noticed that using the advanced setting "Additional CSS class(es)" has no effect at all.

I suggest to
* replace `"style": "safe-svg-block-frontend"` with `"style": "file:../../../dist/safe-svg-block-frontend.css"`  in block.json
* remove `add_action( 'enqueue_block_assets', $n( 'blocks_styles' ) );` in blocks.php

**Comment by LSB-Web-Design** [comment]
Fully agree. I was just about to disable this plugin on all our sites after using it for years because of this. Will follow this issue closely and wait for it to be resolved in the next release.

**Comment by rolf-yoast** [comment]
@IanDelMar I fully agree with it. But I would instead of link to the file, I would register the css and then keep the registered name asset. That way you can also keep the versioning in the file to bust the cache on a new release. And I would do the same for the javascript.

That way you don't have to go down the directory tree to the file.

**Comment by IanDelMar** [comment]
> I fully agree with it. But I would instead of link to the file, I would register the css and then keep the registered name asset. That way you can also keep the versioning in the file to bust the cache on a new release. And I would do the same for the javascript.

Doesn't `"style": "file:../../../dist/safe-svg-block-frontend.css"` add the CSS inline on pages that use the block and hence does not need cache busting? That's why I suggested to go that route.

The frontend JS file is empty. It's an [outdated method](https://developer.wordpress.org/reference/functions/wp_localize_script/#more-information) of adding a global object `safe_svg_personalizer_params` that holds the URL to admin-ajax.php and a nonce - for whatever reason (it's not used anywhere). [`wp_add_inline_script()`](https://developer.wordpress.org/reference/functions/wp_add_inline_script/) with a dummy handle should be used instead.

**Comment by dkotter** [comment]
Thanks all for the reports and helpful notes. I've opened PR #112 to address these issues. If anyone has time to test that out and verify it works as expected, that would be greatly appreciated. Thanks!
